nginx:
  image: "nginx:latest"
  container_name: nginx
  volumes:
    - $PWD:/code
    - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
    - $PWD/log:/var/log/nginx/
  ports:
    - 5000:80
  restart: always
